# Generated by Django 5.0.7 on 2024-09-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'Vip'), ('GENERAL', 'General')], default='General', max_length=10),
        ),
    ]
