# Generated by Django 5.0.7 on 2024-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_catering_eventlogistics_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlogistics',
            name='equipments',
        ),
        migrations.AddField(
            model_name='eventlogistics',
            name='equipments',
            field=models.ManyToManyField(to='event.equipments'),
        ),
    ]
