# Generated by Django 5.0.7 on 2024-09-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_ticket_price_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_due',
            new_name='amount',
        ),
    ]
