# Generated by Django 5.0.7 on 2024-09-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='status',
        ),
        migrations.AddField(
            model_name='attendee',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
