# Generated by Django 5.0.7 on 2024-09-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_attendee_status_attendee_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='message',
        ),
    ]
