# Generated by Django 5.0.7 on 2024-09-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_attendee_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.attendee'),
        ),
    ]
