# Generated by Django 5.0.7 on 2024-09-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_invoice_attendee_communication_receipt_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event_id',
            new_name='event',
        ),
    ]
