# Generated by Django 5.0.7 on 2024-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_ticket_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
