# Generated by Django 5.0.7 on 2024-09-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_event_id_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
    ]
