# Generated by Django 5.0.7 on 2024-09-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_reservation_user_remove_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
