# Generated by Django 5.0.7 on 2024-09-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_reservation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
